version: '2.0'
services:
  ai-chat-app:
    image: overshard/ai-art
    params:
      storage:
        data:
          mount: $(pwd)/data:/data
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - gpus=all
      - v=$(pwd)/data:/data
profiles:
  compute:
    ai-chat-app:
      resources:
        cpu:
          units: 4
        memory:
          size: 12Gi
        storage:
          - size: 100Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
      pricing:
        ai-chat-app:
          denom: uakt
          amount: 10000
deployment:
  ai-chat-app:
    akash:
      profile: ai-chat-app
      count: 1
